apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: task-manager
          image: 643716337997.dkr.ecr.us-east-1.amazonaws.com/task-master:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "terraform-20250409173832660600000001.ckpw4u04e172.us-east-1.rds.amazonaws.com:5432"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Password123"
            - name: DB_NAME
              value: "taskmanager"